TeamMeowBox/MeowBox-iOS

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Order.storyboard
=> test pull request

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift, MeowBox/MeowBox/JangDta/OrderWithoutInfoViewController.swift
=> Conflict Resolution

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift
=> update orderwithinfo first view

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift
=> update orderwithinfo second view

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift
홈에서 '주문하기' 연결 및 주문 스토리보드 에러 수정
=> Update MainVC, Order.stroyboard

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderCompleteViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift
=> add orderwithinfo 2,3,4, complete view

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Kyeahen/Storyboard/Sign.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/SignInViewController.swift
=> Add SignInVC, LoginVC

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Info.plist
=> Add Korean font / Update info.plist

MeowBox/MeowBox/JangDta/Order.storyboard
고양이 정보 필요 주문 1,2 디자인 + 3,4번 초안
=> add design in orderwithinfo 1,2

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift
=> add order branch first

MeowBox/MeowBox/JangDta/Order.storyboard
+<rect key="frame" x="86" y="514" width="7.5" height="20.5"/>
=> -<rect key="frame" x="86" y="514" width="8" height="21"/>

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
홈 사이드바 (미유박스 이야기, 미유박스 후기) 제외하고 화면 전환 끝남
마이페이지 스토리보드 생성했으며 마이페이지에 사이드바 추가 완료 및 (미유박스 이야기, 미유박스 후기) 제외 하고 화면 전환 완료
=> Update Main.storyboard,MainVC / Add MyPage.storyboard, MyPage1VC

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift
=> order view 1,2,3,4 complete

MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
메인 홈 사이드바 '생일박스' 공간 추가
마이페이지 작업 중
=> Update MainVC sideBar / Update MyPage1VC, layout

MeowBox/MeowBox/JangDta/Mypage2.storyboard
=> add settings view

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
마이페이지 화면 전환 완료, 메인 홈 사이드바 컨스트레인 수정 및 버튼 추가
=> Update MyPage1VC, MainVC

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderCompleteViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift, MeowBox/MeowBox/JangDta/SettingViewController.swift
OrderWithInfo 부분  햄버거 바 달 수 있도록 Container에 담음
=> add container in order1

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/Sign.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/LoginPopUp1ViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/LogoutPopUpViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/LogoutSucessPopUpViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/OrderPagePopUpViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/SignInViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/TicketCancelPopUpViewController.swift
마이페이지 사이드바 완성, 회원탈퇴 제외하고 팝업 모두 완성
=> Add PopUp(회원 탈퇴 제외) / Update myPage sideBar

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/Order2ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderCompleteViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift, MeowBox/MeowBox/JangDta/QuestionViewController.swift, MeowBox/MeowBox/JangDta/SuggestViewController.swift
=> update order, mypage2 action

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/QuestionFooterTableViewCell.swift, MeowBox/MeowBox/JangDta/QuestionHeaderTableViewCell.swift, MeowBox/MeowBox/JangDta/QuestionTableViewCell.swift, MeowBox/MeowBox/JangDta/QuestionViewController.swift
=> add suggest expandable tableview

MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/Sign.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyAccountViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
=> Update main sidebar, mypage sidebar

MeowBox/MeowBox/AppDelegate.swift, MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
=> add ticket page 1 complete

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/Kyeahen/Storyboard/Base.lproj/Main.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift
=> update order storyboard

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift
=> update order storyboard 1 view complete

MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/SignInViewController.swift, MeowBox/MeowBox/Util/Function/ExtensionControl.swift
로그인, 회원가입 통신 틀만 만들어놨음 , API 맞춰서 바꾸면댐
=> init Login, Signup network

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/JangDta/NoticeTableViewCell.swift, MeowBox/MeowBox/JangDta/NoticeViewController.swift, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/QuestionViewController.swift, MeowBox/MeowBox/JangDta/SettingViewController.swift, MeowBox/MeowBox/Storyboard/Base.lproj/LaunchScreen.storyboard, MeowBox/MeowBox/Util/Service/APIService.swift
=> add notice view

MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/SignInViewController.swift
로그인 폼만 바꿔주면 될듯
토큰, idx받아오는 코드 아직 안씀
=> 회원가입 통신완료, 로그인은 서버문제로 확인 못함

MeowBox/MeowBox/JangDta/Mypage2.storyboard, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/QuestionViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyAccountViewController.swift
=> 로그인, 회원가입 성공  // 짜잘한 레이아웃 수정

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/Kyeahen/ViewController/LoginViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/SignInViewController.swift, MeowBox/MeowBox/Util/Service/APIService.swift, MeowBox/MeowBox/Util/Service/SignService.swift
=> 로그인, 회원가입 Service 완성! UserDefault 저장!

MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/LoginPopUp1ViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/LogoutPopUpViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/OrderPagePopUpViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/WithdrawalPopUpViewController.swift, MeowBox/MeowBox/Util/Service/SignService.swift
=> 로그아웃, 회원탈퇴 완료

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/TicketViewController.swift, MeowBox/MeowBox/Util/Model/OrderDetailList.swift, MeowBox/MeowBox/Util/Model/OrderListData.swift, MeowBox/MeowBox/Util/Service/OrderService.swift
=> 주문내역 가져오기 완료

MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/Util/Service/MyPageService.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1TicketViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
=> Update myPage1 complete

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/CheckTicketViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift, MeowBox/MeowBox/JangDta/TicketViewController.swift, MeowBox/MeowBox/Kyeahen/Storyboard/MeowBox.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MeowBoxDetailTableViewCell.swift, MeowBox/MeowBox/Util/Model/Cat.swift, MeowBox/MeowBox/Util/Service/OrderService.swift
=> 고양이 이름 유지 가능!

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/CheckTicketViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Util/Service/OrderService.swift, MeowBox/Podfile, MeowBox/Podfile.lock
=> 주문 상세 불러오기 완료

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/Util/Model/LatestAddress.swift, MeowBox/MeowBox/Util/Model/LatestAddressData.swift, MeowBox/MeowBox/Util/Service/OrderService.swift
=> 최근 배송지 가져오기 아직

MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/WithdrawalSucessPopUpViewController.swift, MeowBox/MeowBox/Util/Service/CatService.swift
=> 주문하기페이지 짜잘함 수정, 로그인 액션 분기처리 수정

MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/Util/Iamport/Html5InicisViewController.swift
=> 결제 버그잡기만 남음!! 90%

MeowBox/MeowBox.xcodeproj/project.pbxproj, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/Order1ContainerViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo3ViewController.swift, MeowBox/MeowBox/JangDta/OrderWithInfo4ViewController.swift, MeowBox/MeowBox/JangDta/QuestionViewController.swift, MeowBox/MeowBox/Util/Iamport/Html5InicisViewController.swift, MeowBox/MeowBox/Util/Model/QnA.swift, MeowBox/MeowBox/Util/Model/QnAData.swift, MeowBox/MeowBox/Util/Model/QnAList.swift, MeowBox/MeowBox/Util/Service/OrderService.swift
=> 자주묻는질문 통신 완료

MeowBox/MeowBox/Util/Service/OrderService.swift
=> 정기권 중복체크 통신 완료

MeowBox/MeowBox/Util/Service/OrderService.swift
=> iamport 완성?  95%

MeowBox/MeowBox/Info.plist, MeowBox/MeowBox/JangDta/Order.storyboard, MeowBox/MeowBox/JangDta/OrderWithInfoViewController.swift, MeowBox/MeowBox/JangDta/SuggestViewController.swift, MeowBox/MeowBox/Kyeahen/Storyboard/MyPage.storyboard, MeowBox/MeowBox/Kyeahen/ViewController/MyAccountViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MyPage1ViewController.swift
=> 키보드 안내려가는 부분, 고양이 이름 입력 안 할 시에 부들부들

MeowBox/MeowBox/JangDta/OrderWithInfo2ViewController.swift
=> 주문하기 고양이 등록 부분 수정 !! 팝업 해야함!

MeowBox/MeowBox/JangDta/SuggestViewController.swift, MeowBox/MeowBox/Kyeahen/ViewController/MainViewController.swift, MeowBox/MeowBox/Util/Service/OrderService.swift
=> 제안하기 완전 완성, 주문했을 때 마이페이지 flag로 분기하는 것도 해결!
